development:
  TWITTER_APP_ID: lDjSJ5yzOpbLDrSjyaHl5zCmu
  TWITTER_APP_SECRET: WxF47EwkMj2P36ydqGi12ITWz7JXj6jXws40YZwgyFaGkjSYni
  INSTAGRAM_APP_ID: e42b41e2d96943f6be4815ec0bc378d3
  INSTAGRAM_APP_SECRET: 678bc4e29efd425daf2dfbb68e00b7b0
production:
  TWITTER_APP_ID: lDjSJ5yzOpbLDrSjyaHl5zCmu
  TWITTER_APP_SECRET: WxF47EwkMj2P36ydqGi12ITWz7JXj6jXws40YZwgyFaGkjSYni
  INSTAGRAM_APP_ID: e42b41e2d96943f6be4815ec0bc378d3
  INSTAGRAM_APP_SECRET: 678bc4e29efd425daf2dfbb68e00b7b0